### ISSUE TITLE
Error when I start agent-loop

### ISSUE THREAD

**Issue by tezer** [blorm-network/ZerePy#39]
Hi
I am able to use Twitter API if I do 
`agent-action twitter post-tweet TEST1`

But when I do
`chat` or `agent-loop` I get an error `Error in agent loop: Twitter username is required`

How can I fix it?

**Comment by cygaar** [comment]
im fixing it right now

**Comment by E2OM** [comment]
@tezer 

same here.

Is it fixed? I get: Error in agent loop: User Name ist required
Where do I have to add the user name?
